language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - TESTER_PHP_BIN="php-cgi"
  - TESTER_PHP_BIN="php"

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - env: TESTER_PHP_BIN="php"

  include:
    - php: hhvm
      env: TESTER_PHP_BIN="php"

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

before_script:
  - mkdir tests/temp
  - ./libs/bin/parallel-lint -e php,phpt --exclude libs .

script:
  - ./libs/bin/tester -p $TESTER_PHP_BIN ./tests/
